// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_qDMIuVnBom9KxkoNYQMb1HnTJK5yGYE',
    appId: '1:708919706766:web:9f209c9a449f61e66335df',
    messagingSenderId: '708919706766',
    projectId: 'trustedcars-20e2f',
    authDomain: 'trustedcars-20e2f.firebaseapp.com',
    storageBucket: 'trustedcars-20e2f.firebasestorage.app',
    measurementId: 'G-8S7GC0MMVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0RwfJxQGYUEd6Tyz6SBVgIt8yZMByxoA',
    appId: '1:708919706766:android:71fe4a32652516916335df',
    messagingSenderId: '708919706766',
    projectId: 'trustedcars-20e2f',
    storageBucket: 'trustedcars-20e2f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoe7d1HFhFEb9EdGgnEqLidsa6_UQWuXU',
    appId: '1:708919706766:ios:8048b65609e09e736335df',
    messagingSenderId: '708919706766',
    projectId: 'trustedcars-20e2f',
    storageBucket: 'trustedcars-20e2f.firebasestorage.app',
    iosBundleId: 'com.kdmc.kdmcApp',
  );
}
